### ISSUE TITLE
게임 업데이트시 언어팩이 포함된 resources.assets이 업데이트 된다면?

### ISSUE THREAD

**Issue by aFewThings** [dmc31a42/UnityGameL10nTutorial#4]
강의하신 글 잘 읽었습니다. 덕분에 armello란 게임을 조금씩 번역하게 되었는데요.
armello란 게임은 제가 접했을때부터 여러나라의 언어들을 지원하고 있었습니다.
문제는 오역이 심해서 오역을 수정하고자 resources.assets을 열어보았는데요,
예상대로 'korean'이라는 TextAsset이 있었고 수정하기 용이하게 되어있었습니다.

서두가 길었네요.
강의에선 TextAsset을 수정하게 되면 resources.assets에 저장하게 되는데 
만약에 게임 업데이트가 이루어진다면 TextAsset과 무관한 업데이트라 하더라도 변경된 resources.asset을 위해 다시금 수정작업을 해주어야 되는건가요?

**Comment by dmc31a42** [comment]
예상하신대로 맞습니다. 업데이트할 때 reousrces.assets을 (대부분) 통채로 덮어씌웁니다. 그래서 업데이트해서 번역해둔게 풀리면 다시 resources.assets에 작업하신 TextAsset을 넣어주셔야 합니다.
패치프로그램을 손쉽게 만들 수 있는 프로그램을 만드려고는 하는데 여러가지 일이 겹처서 계속 늦어지네요

**Comment by dmc31a42** [comment]
그리고 게임 버전이 올라가면 해당 TextAsset의 PathID도 같이 바뀔껍니다.

**Comment by aFewThings** [comment]
정말 감사합니다! 도움이 많이 됬습니다.
