### ISSUE TITLE
I2 Localization 에셋을 사용하는 게임의 한글화

### ISSUE THREAD

**Issue by PlAn-K** [dmc31a42/UnityGameL10nTutorial#5]
I2 Localization 에셋을 사용하는 게임을 한글화 해보고자 합니다. (UABE를 통해서 에셋을 파악하였습니다.)

관련하여 찾아보니 구글 스프레드시트로 동기화되어 실시간으로 번역이 적용되는 에셋 같은데, 유저가 한글화하여 패치를 적용할 방법은 없을까요?

**Comment by dmc31a42** [comment]
그 I2 Localization 에셋에 기록되어있는 스프레드시트 주소를 바꾸면 될 것으로 보이나 지금 아시안게임이...

**Comment by PlAn-K** [comment]
우승이네요! 와아아! (..)

제가 Notepad++로 확인하고 UBAE로 파일을 뜯어서 수정하는 수준밖에 안 되서, 방법을 대충이나마 알려주실 수 있을지.. T^T (그리고, 기존 스프레드시트를 가져올 수 없지 않나요?)

**Comment by dmc31a42** [comment]
어떤 게임인지 알려주셔야 어떻게 작동하는 지를 확인할 수 있습니다.
어떤 게임인지 알려주세요

**Comment by PlAn-K** [comment]
Two Point Hospital이라는 게임입니다.

**Comment by PlAn-K** [comment]
계속 만지작 거리다 보니 I2 Localization에서 사용되는 Google Web Service API 주소(..)는 찾아내긴 하였는데, 직접 해당 구글 웹 서비스를 보고 코드를 확인하지 않는 한 스프레드시트를 가져올 방법이 없네요. (과거에는 직접 스프레드시트와 동기화한 것으로 보이는데 구글에서 Web Service API, 매크로 도입한 이후로 변경한 모양입니다.) 

아무래도 힘들 것 같네요.. 도움 주셔서 감사합니다.

**Comment by dmc31a42** [comment]
이게 globalgamemanagers assets을 통해서 열면 container가 보이는데 그 중 i2languages(또는 Type이  MonoBehaviour : I2.Loc.LanguageSource인 놈을 찾아서 Export Dump 하고, mTerms 에 있는 내용을 수정하면 되는데, 문제는 여기에 사용된 TMPro 폰트가 버그가 있는지 해상도를 제대로 처리 못합니다. 그래서 글자가 제대로 출력이 안되요.

**Comment by dmc31a42** [comment]
그리고 Google_WebServiceURL에 있는거 접속해봐도 딱히 뭔가 기능을 하는 것 같아 보이지는 않았습니다.

**Comment by PlAn-K** [comment]
보니까 폰트는 중국어 같은 경우는 Noto Sans를 사용하는 것 같은데요?

**Comment by dmc31a42** [comment]
만약 중국어폰트가 한국어도 된다면 다행인데 안되면 약간 특수한방법을 써야할겁니다. 먼저 제가 이야기한대로 언어파일 중 중국어쪽을
수정해보고 적용한뒤에 실행해보세요

2018년 9월 2일 (일) 22:53, Seungjun Lee <notifications@github.com>님이 작성:

**Comment by PlAn-K** [comment]
감사합니다.

어.. UABE를 이용해서 Export Dump까지 하여 수정까지 마친 상태인데. 다시 Import하여 저장을 하면 resources.assets로 저장이 되는데 다른 방법이 있나요? 늦은 밤에 죄송합니다.

**Comment by dmc31a42** [comment]
globalgamemanagers assets을 열었다고 해도 UABE에 globalgamemanagers에셋만 보이는 것은 아닙니다. globalgamemanagers이 의존성을 가지고 있는 모든 assets을 열게 됩니다. assets을 수정한다해도 저장하는건 수정된 assets이지 처음에 열었던 globalgamemanagers이 아닐 수 도 있습니다. resources.assets이 i2language가 들어있는 assets이 맞기에 에셋을 수정하면 resources.assets을 저장하려 하는 것입니다. UABE에서 해당 assets이 열려있으니 resources.assets.mod로 저장하고 UABE가 종료되면 resources.assets을 resources.assets.orig등으로 이름을 바꾸고 resources.assets.mod를 resources.assets로 이름을 바꾸면 됩니다.

**Comment by PlAn-K** [comment]
감사합니다. 계속 진행해보다가 어려움이 생기면 추가적으로 문의 드리겠습니다. 👍

**Comment by PlAn-K** [comment]
예상했던대로 일단 한국어 표시는 되지 않네요. 한국어 표시를 하려면 Noto Sans CJK KR 폰트(Noto Sans 한국어 폰트)를 추가해야 할 것 같은데 말씀하셨다싶이 TMPro(TextMesh Pro) 에셋을 사용하는 것 같네요. 일이 복잡해지네요.. :(

**Comment by dmc31a42** [comment]
그래서 TMPro Font를 수정했는데, 다른 게임과는 달리 불러온 Assets의 해상도를 제대로 인식하지 않습니다. 그래서 폰트가 이상하게 출력이 되요.일단 저해상도로 폰트를 다시 만들어보고 그래도 안되면 어떻게 할 방도가 없습니다. 그 버그가 고쳐지기를 기다릴 수 밖에요

**Comment by dmc31a42** [comment]
일단 이 작업은 잠시후에 할 예정입니다. 지금은 딴거 하고 있어서요

**Comment by dmc31a42** [comment]
@PlAn-K 늦은저녁에 죄송합니다.
상상도 못할 버그때문에 삽질한거였고, 원래 TMPro 플러그인을 사용한 모든 게임에 적용되는 방법을 사용하여 한글화할 수 있습니다. 다만..... 정말 예상치 못한 버그때문에....
![image](https://user-images.githubusercontent.com/13437953/44959056-b1698980-af23-11e8-9b6c-d2d64d16ffe0.png)
자세한 내용은 내일, 매일 7시 이후로 연락하시면 알려드릴 수 있습니다.

**Comment by PlAn-K** [comment]
아아, 잠시 여행을 다녀 와서 늦어서 죄송합니다. 어떻게 따로 연락 드릴까요?

**Comment by dmc31a42** [comment]
스팀: DevilMayCry31a42,
디스코드: nakwonelec#1553
중에서 편한걸로 친츄해주세요

2018년 9월 5일 (수) 18:15, Seungjun Lee <notifications@github.com>님이 작성:

**Comment by PlAn-K** [comment]
스팀 친구 추가 보내놨습니다! 👍
